/**
 * Calculator Type Definitions
 * Generated by API generator
 * 
 * ⚠️ IMPORTANT: Use camelCase for all properties!
 * Backend returns snake_case, but services/api.ts converts to camelCase automatically.
 */

export interface InputField {
  name: string;
  label: string;
  type: 'number' | 'text' | 'select';
  unit?: string;
  min?: number;
  max?: number;
  options?: string[];
}

export interface InterpretationRule {
  condition: string;
  interpretation: string;
  severity: 'normal' | 'caution' | 'warning' | 'danger' | 'critical';
}

export interface Calculator {
  id: string | number;
  name: string;
  description: string;
  formula: string;
  category: string;
  inputFields: InputField[];
  interpretationRules: InterpretationRule[];
  createdAt: string;
  updatedAt: string;
}

export interface CreateCalculatorInput {
  name: string;
  description: string;
  formula: string;
  category: string;
  inputFields: InputField[];
  interpretationRules: InterpretationRule[];
}

export interface UpdateCalculatorInput {
  name?: string;
  description?: string;
  formula?: string;
  category?: string;
  inputFields?: InputField[];
  interpretationRules?: InterpretationRule[];
}

export type CalculatorResponse = Calculator;
export type CalculatorsResponse = Calculator[];
