/**
 * Calculators Store
 * Zustand store for managing calculators state
 * Generated by API generator
 */

import { create } from 'zustand';
import { calculatorsService } from '@/services/calculators';
import type { Calculator, CreateCalculatorInput, UpdateCalculatorInput } from '@/types/calculators';

interface CalculatorsStore {
  // State
  items: Calculator[];
  loading: boolean;
  error: string | null;

  // Actions
  fetchAll: () => Promise<void>;
  reset: () => void;
}

export const useCalculatorsStore = create<CalculatorsStore>((set) => ({
  items: [],
  loading: false,
  error: null,

  fetchAll: async () => {
    set({ loading: true, error: null });
    try {
      let items = await calculatorsService.getAll();
      // Normalize category to a sortable id (lowercase), ensure id is string
      // and ensure inputFields exists (supports `input_fields` from seed JSON)
      items = items.map((it) => ({
        ...it,
        id: String(it.id),
        category: it.category || '' ,
        categoryId: String(it.category || '').toLowerCase(),
        inputFields: (it as any).inputFields || (it as any).input_fields || [],
      } as any));
      set({ items, loading: false });
    } catch (error: any) {
      console.error('Failed to fetch calculators:', error);
      set({ error: error.message || 'Failed to load calculators', loading: false });
    }
  },

  reset: () => set({ items: [], loading: false, error: null }),
}));
