/**
 * Calculators Store
 * Zustand store for managing calculators state
 * Generated by API generator
 */

import { create } from 'zustand';
import { calculatorsService } from '@/services/calculators';
import type { Calculator, CreateCalculatorInput, UpdateCalculatorInput } from '@/types/calculators';

interface CalculatorsStore {
  // State
  items: Calculator[];
  loading: boolean;
  error: string | null;

  // Actions
  fetchAll: () => Promise<void>;
  reset: () => void;
}

export const useCalculatorsStore = create<CalculatorsStore>((set) => ({
  items: [],
  loading: false,
  error: null,

  fetchAll: async () => {
    set({ loading: true, error: null });
    try {
      const items = await calculatorsService.getAll();
      set({ items, loading: false });
    } catch (error: any) {
      console.error('Failed to fetch calculators:', error);
      set({ error: error.message || 'Failed to load calculators', loading: false });
    }
  },

  reset: () => set({ items: [], loading: false, error: null }),
}));
