/**
 * CalculationResults Store
 * Zustand store for managing calculation_results state
 * Generated by API generator
 */

import { create } from 'zustand';
import { calculationResultsService } from '@/services/calculation_results';
import type { CalculationResult, CreateCalculationResultInput, UpdateCalculationResultInput } from '@/types/calculation_results';

interface CalculationResultsStore {
  // State
  items: CalculationResult[];
  loading: boolean;
  error: string | null;

  // Actions
  fetchAll: () => Promise<void>;
  addItem: (data: CreateCalculationResultInput | FormData) => Promise<CalculationResult>;
  reset: () => void;
}

export const useCalculationResultsStore = create<CalculationResultsStore>((set) => ({
  items: [],
  loading: false,
  error: null,

  fetchAll: async () => {
    set({ loading: true, error: null });
    try {
      const items = await calculationResultsService.getAll();
      set({ items, loading: false });
    } catch (error: any) {
      console.error('Failed to fetch calculation_results:', error);
      set({ error: error.message || 'Failed to load calculation_results', loading: false });
    }
  },

  addItem: async (data: CreateCalculationResultInput | FormData) => {
    set({ loading: true, error: null });
    try {
      const newItem = await calculationResultsService.create(data);
      set((state) => ({
        items: [newItem, ...state.items],
        loading: false,
        error: null
      }));
      return newItem;
    } catch (error: any) {
      console.error('Failed to create calculation_result:', error);
      set({ error: error.message || 'Failed to create calculation_result', loading: false });
      throw error;
    }
  },

  reset: () => set({ items: [], loading: false, error: null }),
}));
