/**
 * Authentication Service
 * Handles all authentication-related API calls
 * Generated by authentication generator
 */

import { auth } from './firebase';
import { storage } from '@/services/storage';
import type { User } from '@/types/auth';
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut,
  onAuthStateChanged,
  getIdToken,
  User as FirebaseUser,
} from 'firebase/auth';

class AuthService {
  async login({ email, password }: { email: string; password: string }) {
    const result = await signInWithEmailAndPassword(auth, email, password);
    const token = await getIdToken(result.user, true); // Force refresh
    await storage.set('session_token', token);
    await storage.set('uid', result.user.uid);
    return { sessionToken: token, user: { id: result.user.uid, email: result.user.email } } as any;
  }

  async signup({ email, password }: { email: string; password: string }) {
    const result = await createUserWithEmailAndPassword(auth, email, password);
    const token = await getIdToken(result.user, true); // Force refresh
    await storage.set('session_token', token);
    await storage.set('uid', result.user.uid);
    return { sessionToken: token, user: { id: result.user.uid, email: result.user.email } } as any;
  }

  async logout(): Promise<void> {
    await signOut(auth);
    await storage.remove('session_token');
    await storage.remove('uid');
  }

  async getCurrentUser(): Promise<User | null> {
    return new Promise(resolve => {
      const unsubscribe = onAuthStateChanged(auth, user => {
        unsubscribe();
        if (!user) return resolve(null);
        resolve({ id: user.uid, email: user.email } as any);
      });
    });
  }

  async isAuthenticated(): Promise<boolean> {
    const token = await storage.get('session_token');
    return !!token;
  }

  async refreshToken(): Promise<string | null> {
    const user = auth.currentUser;
    if (!user) return null;
    
    try {
      const token = await getIdToken(user, true); // Force refresh
      await storage.set('session_token', token);
      return token;
    } catch (error) {
      console.error('Token refresh failed:', error);
      return null;
    }
  }
}

export const authService = new AuthService();
