/**
 * Calculators API Service
 * Generated by API generator
 */

import { api } from './api';
import type { Calculator, CalculatorResponse, CalculatorsResponse, CreateCalculatorInput, UpdateCalculatorInput } from '../types/calculators';
import { API_BASE_URL } from '../config/api';

class CalculatorsService {
  /**
   * Get all calculators
   */
  async getAll(): Promise<CalculatorsResponse> {
    return api.get<CalculatorsResponse>(`${API_BASE_URL}/api/v1/calculators`);
  }

  /**
   * Get a single calculator by ID
   */
  async getById(id: number): Promise<CalculatorResponse> {
    return api.get<CalculatorResponse>(`${API_BASE_URL}/api/v1/calculators/${id}`);
  }
}

export const calculatorsService = new CalculatorsService();
