/**
 * Calculators API Service
 * Generated by API generator
 */

import type { Calculator, CalculatorResponse, CalculatorsResponse } from '../types/calculators';
import calculatorsData from '../assets/calculators.json';

function slugify(name: string) {
  return name
    .toString()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

class CalculatorsService {
  async getAll(): Promise<CalculatorsResponse> {
    const items: Calculator[] = (calculatorsData as any[]).map((c, idx) => {
      const id = c.id ? String(c.id) : slugify(c.name || `calc-${idx}`);
      const inputFields = c.inputFields || c.input_fields || [];
      // normalize each field object keys if needed
      const normalizedFields = (inputFields as any[]).map((f) => ({
        name: f.name || f.id || f.key,
        label: f.label || f.title || f.display || f.name,
        type: f.type || 'number',
        unit: f.unit,
        options: f.options || [],
        min: f.min,
        max: f.max,
      }));
      return { id, ...c, inputFields: normalizedFields } as Calculator;
    });
    return items as CalculatorsResponse;
  }

  async getById(id: string): Promise<CalculatorResponse> {
    const items: Calculator[] = (calculatorsData as any[]).map((c, idx) => {
      const cid = c.id ? String(c.id) : slugify(c.name || `calc-${idx}`);
      const inputFields = c.inputFields || c.input_fields || [];
      const normalizedFields = (inputFields as any[]).map((f) => ({
        name: f.name || f.id || f.key,
        label: f.label || f.title || f.display || f.name,
        type: f.type || 'number',
        unit: f.unit,
        options: f.options || [],
        min: f.min,
        max: f.max,
      }));
      return { id: cid, ...c, inputFields: normalizedFields } as Calculator;
    });
    const found = items.find(i => String(i.id) === String(id));
    if (!found) throw new Error('Calculator not found');
    return found as CalculatorResponse;
  }
}

export const calculatorsService = new CalculatorsService();
