/**
 * Sign In Screen
 * Generated by authentication generator
 */

import React, { useState } from 'react';
import { View, Text, TextInput, Pressable, ScrollView, ActivityIndicator } from 'react-native';
import { useRouter, Link } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useAuth } from '@/hooks/useAuth';
import { Alert } from '@/utils/alert';

export default function SignInScreen() {
  const router = useRouter();
  const { login, isLoading } = useAuth();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const handleSignIn = async () => {
    if (!email || !password) {
      Alert.alert('Ошибка', 'Пожалуйста, введите email и пароль');
      return;
    }

    try {
      setSubmitting(true);
      await login({ email, password });
      router.replace('/');
    } catch (error) {
      Alert.alert('Ошибка', error instanceof Error ? error.message : 'Не удалось войти');
    } finally {
      setSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <View className="flex-1 items-center justify-center bg-surface">
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <ScrollView className="flex-1 bg-surface">
      <View className="flex-1 p-8 pt-20 pb-20">
        <View className="mb-8">
          <Text className="text-4xl font-bold text-text-primary mb-2">
            Добро пожаловать
          </Text>
          <Text className="text-lg text-text-secondary">
            Войдите, чтобы продолжить
          </Text>
        </View>

        <View className="gap-4 mb-6">
          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Email
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder="Ваш email"
              placeholderTextColor="#9CA3AF"
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              editable={!submitting}
            />
          </View>

          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Пароль
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder="Введите пароль"
              placeholderTextColor="#9CA3AF"
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              editable={!submitting}
            />
          </View>

          <Link href="/forgot-password" asChild>
            <Pressable>
              <Text className="text-sm text-primary text-right">
                Забыли пароль?
              </Text>
            </Pressable>
          </Link>
        </View>

        <Pressable
          onPress={handleSignIn}
          disabled={submitting}
          className="bg-primary py-3 px-6 rounded-lg active:opacity-80 mb-4"
        >
          {submitting ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text className="text-white text-center font-semibold text-base">
              Войти
            </Text>
          )}
        </Pressable>

        <View className="flex-row items-center justify-center gap-1">
          <Text className="text-text-secondary">
            Нет аккаунта?
          </Text>
          <Link href="/sign-up" asChild>
            <Pressable>
              <Text className="text-primary font-semibold">
                Зарегистрироваться
              </Text>
            </Pressable>
          </Link>
        </View>
      </View>
      <StatusBar style="auto" />
    </ScrollView>
  );
}
