/**
 * Sign Up Screen
 * Generated by authentication generator
 */

import React, { useState } from 'react';
import { View, Text, TextInput, Pressable, ScrollView, ActivityIndicator } from 'react-native';
import { useRouter, Link } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useAuth } from '@/hooks/useAuth';
import { Alert } from '@/utils/alert';

// Password validation rules
const MIN_PASSWORD_LENGTH = 4;

export default function SignUpScreen() {
  const router = useRouter();
  const { signup, isLoading } = useAuth();

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [passwordConfirmation, setPasswordConfirmation] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const handleSignUp = async () => {
    if (!name || !email || !password || !passwordConfirmation) {
      Alert.alert('Ошибка', 'Пожалуйста, заполните все поля');
      return;
    }

    if (password !== passwordConfirmation) {
      Alert.alert('Ошибка', 'Пароли не совпадают');
      return;
    }

    if (password.length < MIN_PASSWORD_LENGTH) {
      Alert.alert('Ошибка', `Пароль должен содержать минимум ${MIN_PASSWORD_LENGTH} символов`);
      return;
    }

    try {
      setSubmitting(true);
      await signup({
        name,
        email,
        password,
        passwordConfirmation,
      });
      router.replace('/');
    } catch (error) {
      Alert.alert('Ошибка', error instanceof Error ? error.message : 'Не удалось зарегистрироваться');
    } finally {
      setSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <View className="flex-1 items-center justify-center bg-surface">
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <ScrollView className="flex-1 bg-surface">
      <View className="flex-1 p-8 pt-20 pb-20">
        <View className="mb-8">
          <Text className="text-4xl font-bold text-text-primary mb-2">
            Создать аккаунт
          </Text>
          <Text className="text-lg text-text-secondary">
            Зарегистрируйтесь, чтобы начать
          </Text>
        </View>

        <View className="gap-4 mb-6">
          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Имя
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder="Ваше имя"
              placeholderTextColor="#9CA3AF"
              value={name}
              onChangeText={setName}
              editable={!submitting}
            />
          </View>

          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Email
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder="Ваш email"
              placeholderTextColor="#9CA3AF"
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              editable={!submitting}
            />
          </View>

          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Пароль
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder={`Минимум ${MIN_PASSWORD_LENGTH} символов`}
              placeholderTextColor="#9CA3AF"
              value={password}
              onChangeText={setPassword}
              secureTextEntry
              editable={!submitting}
            />
          </View>

          <View>
            <Text className="text-sm font-medium text-text-primary mb-2">
              Подтверждение пароля
            </Text>
            <TextInput
              className="bg-surface-elevated border border-border rounded-lg px-4 py-3 text-text-primary"
              placeholder="Повторите пароль"
              placeholderTextColor="#9CA3AF"
              value={passwordConfirmation}
              onChangeText={setPasswordConfirmation}
              secureTextEntry
              editable={!submitting}
            />
          </View>
        </View>

        <Pressable
          onPress={handleSignUp}
          disabled={submitting}
          className="bg-primary py-3 px-6 rounded-lg active:opacity-80 mb-4"
        >
          {submitting ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text className="text-white text-center font-semibold text-base">
              Зарегистрироваться
            </Text>
          )}
        </Pressable>

        <View className="flex-row items-center justify-center gap-1">
          <Text className="text-text-secondary">
            Уже есть аккаунт?
          </Text>
          <Link href="/sign-in" asChild>
            <Pressable>
              <Text className="text-primary font-semibold">
                Войти
              </Text>
            </Pressable>
          </Link>
        </View>
      </View>
      <StatusBar style="auto" />
    </ScrollView>
  );
}
